name: interactive_login
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "2.19.2"
  flutter: "3.7.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  rive: any
  flutter_hooks: 0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/teddy.riv
