name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
      - name: Flutter GH pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /${{ github.event.repository.name }}/